name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: | 
        cd Mock2022SkeletonCode
        dotnet restore
    - name: Build
      run: | 
        cd Mock2022SkeletonCodedotnet 
        build --no-restore
    - name: Test
      run: | 
        cd Mock2022SkeletonCode
        dotnet test --no-build --verbosity normal
